
server:
  port: 7071

jwt:
  secret: myjwttest
  token-valid-in-millisecond: 60000


spring:
  application:
    name: user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chomini?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://192.168.0.27:8761/eureka
      defaultZone: http://127.0.0.1:8761/eureka